//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Country
    {
        public Country()
        {
            this.Hotels = new HashSet<Hotel>();
        }
    
        public int CountryId { get; set; }
        [Required]
        [Display(Name = "Country Name")]
        public string CountryName { get; set; }
    
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}
