//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public string Status { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
