//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Room
    {
        public Room()
        {
            this.Reservations = new HashSet<Reservation>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int RoomId { get; set; }
        [Required]
        [Display(Name = "Room Number")]
        public string RoomNumber { get; set; }
        [Required]
        [Display(Name = "Class Name")]
        public string ClassName { get; set; }
        [Required]
        [Display(Name = "Max Guest")]
        public Nullable<int> MaxGuest { get; set; }
        [Required]
        public Nullable<int> Price { get; set; }
        [Required]
        public string Description { get; set; }
        public string Image { get; set; }
        [Required]
        public Nullable<int> HotelId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
